---
- name: Update and install packages on different machines
  hosts: all
  become: yes
  tasks:
    - name: Update apt cache on Debian/Ubuntu
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Update yum cache on CentOS/RedHat
      yum:
        update_cache: yes
      when: ansible_os_family == "RedHat"

- name: Install nginx on nginx_servers
  hosts: nginx_servers
  become: yes
  tasks:
    - name: Install nginx on Debian/Ubuntu
      apt:
        name: nginx
        state: present
      when: ansible_os_family == "Debian"

    - name: Install nginx on CentOS/RedHat
      yum:
        name: nginx
        state: present
      when: ansible_os_family == "RedHat"

- name: Install Java on java_servers
  hosts: java_servers
  become: yes
  tasks:
    - name: Install Java on Debian/Ubuntu
      apt:
        name: default-jdk
        state: present
      when: ansible_os_family == "Debian"

    - name: Install Java on CentOS/RedHat
      yum:
        name: java-1.8.0-openjdk
        state: present
      when: ansible_os_family == "RedHat"

      