# This YAML file Installs Nginx on EC2 Intsances based on thier OS family
---
- name: Install and configure Nginx
  hosts: web_nodes
  become: true
  tasks:
    - name: Install Nginx
      yum:
        name: nginx
        state: present
      when: ansible_os_family == "Amazon_Linux"

      - name: Install Nginx
      apt:
        name: nginx
        state: present
      when: ansible_os_family == "Ubuntu"

    - name: Start and enable Nginx service
      service:
        name: nginx
        state: started
        enabled: yes
      when: ansible_os_family == "Amazon_Linux" or ansible_os_family == "Ubuntu"


